services:
  backend:
    build:
      context: ./server2
      dockerfile: Dockerfile
    container_name: aotygen-server
    ports:
      - "8080:8080"
    env_file: server2/.env
    depends_on:
      - redis

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: aotygen-client
    ports:
      - "5173:80"
    depends_on:
      - backend

  redis:
    image: redis:7-alpine
    container_name: aotygen-redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  redisdata:
